### ISSUE TITLE
Implement a WebAssembly runner function

### ISSUE THREAD

**Issue by psarna** [libsql/libsql#17]
A user-defined function capable of running WebAssembly code should be defined (and registered with `sqlite3_create_function`).

Its final specification should be subject to discussion, but the proposed format could look like that (pseudo-code):
```
fn run_wasm(wasm_module: blob, function_name: string, args...)
```

The function would accept a blob with compiled WebAssembly as its first argument, the Wasm function name to look up and execute as the second argument, and forward the rest of the arguments as is to this Wasm function to be executed.

This function can later be a foundation for allowing users to create and register arbitrary Wasm functions right from the CQL interface (esp. with some syntactic sugar to make it pretty: https://github.com/libsql/libsql/issues/18).

An important design decision is to pick a WebAssembly runtime for executing the modules. A preliminary list to consider:
 - wasmtime (https://github.com/bytecodealliance/wasmtime): feature-complete, I have some experience with it
 - wasmer (https://github.com/wasmerio/wasmer) reportedly faster
 - a generic interface which allows picking one, the other, or any other runtime

Right now I'm biased in favor of wasmtime, but since I saw @losfair's activity in this repository (welcome!!!) I can't resist asking - would you recommend wasmer instead? Any recommmendations for/against it?

**Comment by losfair** [comment]
Wasmtime and Wasmer both support [wasm-c-api](https://github.com/WebAssembly/wasm-c-api) (with some custom extensions) btw. `#ifdef`-ing away the differences and supporting both runtimes shouldn't be too much work.

**Comment by psarna** [comment]
I gathered my experiments in a repository: https://github.com/psarna/libsql_run_wasm_example. I'll later proceed with integrating it into libSQL core, but that will be lots of preprocessor macros and configuration boilerplate to make sure that it also builds fine for people not interested in WebAssembly integration. And the feature itself should definitely be opt-in during compilation, because the Wasm runtime weighs an order of magnitude more than the entire sqlite3 codebase.
