### ISSUE TITLE
Row read counts with queries involving descending ordering are miscalculated

### ISSUE THREAD

**Issue by CodingDoug** [libsql/libsql#226]
Assuming that this query returns two rows, it counts two rows read correctly:

```sql
select uid, score from example order by score limit 2;
```

However, descending order counts just 1:

```sql
select uid, score from example order by score desc limit 2;
```

In general, for limits greater than 1, it seems descending queries with limits count one fewer read than they should.

**Comment by psarna** [comment]
Thanks for reporting, it's generally because `OP_Last` opcode, which is used instead of `OP_Rewind`, is not bumping the metrics properly.
