### ISSUE TITLE
Pragma random rowid by default for new tables

### ISSUE THREAD

**Issue by dezren39** [libsql/libsql#241]
I think it may be beneficial to be able to configure the default create table rowid behavior.

**Comment by penberg** [comment]
Hey @dezren39, in general, we tend to prefer SQLite defaults for compatibility. @psarna what do you think?

**Comment by dezren39** [comment]
I kinda came to similar conclusion sometime after opening. I'm good to close, whatever works for me. Thanks!

**Comment by psarna** [comment]
Yeah, let's keeps the defaults compatible with SQLite. And I actually rely on consecutive rowid numbers in my https://sorry.idont.date weekend project, treating incoming mails as very crude time series, so I'm a user of the default behavior (:
