### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by zeritonius** [libsql/libsql#26]
SQLite is public domain, both as source and as documentation.

I'm not a lawyer, but as far as I know, the Apache license is more restrictive than the public domain one, and it applies to the software, not also to the documentation.

I was wondering if you're willing to make libSQL public domain or at least MIT from the start. From what I understand, MIT license also applies to the documentation, and it's easier to understand, in my (and some others') opinion than Apache license.

Thank you.

**Comment by zeritonius** [comment]
Thank you for considering MIT license.

If you dual license, could you, please, specify explicitly that the user can choose one of the available licenses? "Apache and MIT" is confusing to some, as they think they might need to follow both (actually, some projects force the user to follow both) while "MIT or Apache, at your choosing" looks crystal clear to me.

**Comment by SamuelMarks** [comment]
What you can do, is use SPDX expressions to make all parties happy. For example: `Apache-2.0 OR MIT OR CC0` would give you the benefits of public-domain (CC0), of patent issuance (Apache-2.0), and of interoperability compliance with various GPL and LGPL levels (MIT).

That's my recommendation anyway: `Apache-2.0 OR MIT OR CC0`
