### ISSUE TITLE
Implement Rows::to_column_names()

### ISSUE THREAD

**Issue by penberg** [libsql/libsql#267]
for rusqlite compatibility

**Comment by aqrln** [comment]
Note: turned out it was actually implemented on user side and not in rusqlite. The actual API in rusqlite is `Rows::as_ref` that returns `Option<&Statement<'stmt>>` and `Statement::column_names` that returns `Vec<&str>`.

**Comment by penberg** [comment]
@aqrln Aah, right, I got confused somehow and thought it was in rusqlite when I checked. thanks
