### ISSUE TITLE
[compilation]: configure should fail when `--enable-readline` is given but no readline library found

### ISSUE THREAD

**Issue by vegerot** [libsql/libsql#65]
I just spent 20 minutes trying to build libsql on Debian with `--enable-readline`, trying to figure out why I couldn't get readline to work.  It wasn't until I looked at the Makefile I realized I had no readline-compatible library installed.

I think that when `--enable-readline` is explicitly given and libedit or readline is not installed, the configure program should return a non-zero exit code

**Comment by psarna** [comment]
@vegerot could you re-check the new script? #66  I tested on latest Docker image for Debian and it indeed errors out now instead of silently disabling readline. Thanks for reporting!

**Comment by psarna** [comment]
let's assume it worked and reopen otherwise
