### ISSUE TITLE
./configure; make; make install throws error

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [libsql/libsql#71]
This error shows up which goes indefinitely!

[file.log](https://github.com/libsql/libsql/files/10033888/file.log)

**Comment by psarna** [comment]
@Abdur-rahmaanJ please also post the exact parameters passed to ./configure calls. Also, for a start, could you retry after `make clean`? Such errors can happen if there are stale files from previous configurations in your working directory.

For the record, I just tried ./configure && make on current libsql main branch and it worked just fine. I also tried the raw gcc command that failed in your logs and it runs smoothly.

**Comment by Abdur-rahmaanJ** [comment]
Works!
