### ISSUE TITLE
Feat: Add WasmEdge as a UDF runtime

### ISSUE THREAD

**Issue by juntao** [libsql/libsql#94]
Happy new year! And congratulations on [the successful incorporation](https://github.com/libsql/libsql/pull/45) of Wasm UDFs into the libsql project! As we had discussed in the PR, we would like to explore adding WasmEdge as an option for UDFs in libsql. The rationales are as follows. 

* WasmEdge is one of the [smallest](https://github.com/libsql/libsql/pull/45#issuecomment-1310226897) and [fastest](https://wasmedge.org/book/en/features.html) Wasm runtimes. 
* WasmEdge supports [rich APIs](https://wasmedge.org/book/en/features.html) in the Wasm runtime beyond the WASI spec, such as async sockets. That enables more complex UDFs. 
* Docker starts to [bundle and ship WasmEdge](https://docs.docker.com/desktop/wasm/) in every copy of Docker Desktop from 4.15. That allows over 10M Docker developers to create and test Wasm functions using WasmEdge APIs.  
* Fedora and Red Hat EPEL [ship with WasmEdge](https://packages.fedoraproject.org/pkgs/wasmedge/wasmedge/index.html). They could further reduce the size of libsql’s install package. 

WasmEdge supports a comprehensive [Rust SDK](https://github.com/second-state/wasmedge-rustsdk-examples) and [C SDK](https://wasmedge.org/book/en/sdk/c.html) to make integration easier. I think we could provide a compile time or runtime flag to switch between supported Wasm runtimes. Please let me know what you think! Thanks.

**Comment by psarna** [comment]
Thanks! I even experimented a little bit with WasmEdge API back in November - https://github.com/psarna/libsql/commits/wasmedge_poc. This branch is very much not up-to-date, but once I finish some other priority items, I'll get back to it

**Comment by juntao** [comment]
Please let us know how we can be of assistance. I think the integration still needs to be done by the libsql team. But if there is any questions / feature requests for the WasmEdge SDK, we would be more than happy to help.

And after the integration, we could help developing some use cases. 🤝

**Comment by psarna** [comment]
Update: I was preempted from UDF for quite a while, but I spent some time this week to recover and rebase my early patch for WasmEdge support. I have ints and floats working as well as a functional CI (which does not pass tests yet, expected). I'm also on vacation next week, but right after that I'll try to deliver a working WasmEdge support. Then we can figure out a nice demo or use case. Thanks!

**Comment by juntao** [comment]
That sounds great! Look forward to seeing it running!

**Comment by psarna** [comment]
@juntao and see you at wasmio.tech! (:

**Comment by psarna** [comment]
#131 now has all the types working, but it's still not mergeable - the test suite needs to be updated in order to cover it, and we should perhaps add some automation for downloading libwasmedge if somebody decides to use it.

(I'm on archlinux where some good person already created an [AUR package for wasmedge](https://aur.archlinux.org/packages/wasmedge), but rest of the distros are not covered to the best of my knowledge)

**Comment by juntao** [comment]
WasmEdge has official packages on Fedora and Red Hat EPEL

https://packages.fedoraproject.org/pkgs/wasmedge/wasmedge/index.html

🤝

**Comment by psarna** [comment]
Perfect!

**Comment by juntao** [comment]
> perhaps add some automation for downloading libwasmedge if somebody decides to use it

I think the script can just get the slim version of WasmEdge runtime from our release page like this:

https://github.com/WasmEdge/WasmEdge/releases/download/0.11.2/WasmEdge-slim-runtime-0.11.2-manylinux2014_x86_64.tar.gz

The `lib64/libwasmedge.so` linked file is the one we need for Linux. Both x86_64 and aarch64 versions are available on the release asset page.

**Comment by psarna** [comment]
Yeah, that's precisely what I've done in the CI script that runs on Ubuntu 👌
